# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Resolve context
description: Определить контекст вызова workflow

inputs:
  mode:
    required: true
    type: string
    default: feature
    description: Режим (release | feature | rebuild)

  tag:
    required: false
    type: string
    default: ""
    description: Тег, указываемый при ручной пересборке

  registry:
    required: false
    type: string
    default: ghcr.io
    description: Регистр образов

  image-name:
    required: false
    type: string
    default: ${{ github.repository }}
    description: Имя образа

outputs:
  ref:
    value: ${{ steps.resolve.outputs.ref }}
    description: Git-ref

  version:
    value: ${{ steps.resolve.outputs.version }}
    description: Версия на основе git-тега

  image-tag:
    value: ${{ steps.resolve.outputs.image-tag }}
    description: Версия на основе git-тега (например, v1.2.3)

  image-references:
    value: ${{ steps.resolve.outputs.image-references }}
    description: >
      Список имен образов в формате
      <registry>/\<image-name\>:\<version\>

runs:
  using: composite
  steps:
    - name: 🔍 Resolve context
      id: resolve
      shell: bash
      run: |
        set -euo pipefail

        REPO="${{ inputs.registry }}/${{ inputs.image-name }}"
        MODE="${{ inputs.mode }}"

        if [[ "$MODE" == "feature" ]]; then
          COMMIT_HASH="${{ github.sha }}"
          REF="${GITHUB_REF}"
          VERSION=""
          TAG="$COMMIT_HASH"
          IMAGE_REFERENCES="$REPO:$TAG"

        elif [[ "$MODE" == "release" ]]; then
          REF="${GITHUB_REF}"
          VERSION="${GITHUB_REF#refs/tags/v}"
          TAG=VERSION
          IMAGE_REFERENCES="$REPO:$TAG, $REPO:latest"

        elif [[ "$MODE" == "rebuild" ]]; then
          REF="refs/tags/${{ inputs.tag }}"
          VERSION="${{ inputs.tag }}"
          TAG=VERSION
          IMAGE_REFERENCES="$REPO:$TAG"

        else
          echo "❌ Неизвестный режим mode: $MODE"
          exit 1
        fi

        echo "ref=$REF" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "image-tag=$TAG" >> $GITHUB_OUTPUT
        echo "image-references=$IMAGE_REFERENCES" >> $GITHUB_OUTPUT
