# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Resolve context
description: Определить контекст вызова workflow

inputs:
  mode:
    required: true
    type: string
    default: feature
    description: Режим (release | feature | rebuild)

  tag:
    required: false
    type: string
    default: ""
    description: Тег, указываемый при ручной пересборке

  registry:
    required: false
    type: string
    default: ghcr.io
    description: Регистр образов

  image-name:
    required: false
    type: string
    default: ${{ github.repository }}
    description: Имя образа

outputs:
  ref:
    value: ${{ steps.resolve.outputs.ref }}
    description: Git-ref

  version:
    value: ${{ steps.resolve.outputs.version }}
    description: Версия на основе git-тега

  image-tags:
    value: ${{ steps.resolve.outputs.image-tags }}
    description: Список тегов для docker-образа

runs:
  using: composite
  steps:
    - name: 🔍 Resolve context
      id: resolve
      shell: bash
      run: |
        set -euo pipefail

        REPO=${{ inputs.registry }}/${{ inputs.image-name }}}
        MODE="${{ inputs.mode }}"

        if [[ "$MODE" == "release" ]]; then
          REF="${GITHUB_REF}"
          VERSION="${GITHUB_REF#refs/tags/v}"
          IMAGE_TAGS="$REPO:$VERSION, $REPO:latest"

        elif [[ "$MODE" == "rebuild" ]]; then
          REF="refs/tags/${{ inputs.tag }}"
          VERSION="${{ inputs.tag }}"
          IMAGE_TAGS="$REPO:$VERSION"

        elif [[ "$MODE" == "feature" ]]; then
          REF="${GITHUB_REF}"
          VERSION="${GITHUB_SHA}"
          IMAGE_TAGS="$REPO:$VERSION"

        else
          echo "Unknown mode"
          exit 1
        fi

        echo "ref=$REF" >> $GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "image-tags=$IMAGE_TAGS" >> $GITHUB_OUTPUT
