# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Republish NPM Package with Tag (re-release manually)
description: >
  Сборка и повторная публикация NPM пакета с указанным git-тегом вида 'v*.*.*'.
  Запускать вручную через UI

on:
  workflow_dispatch:
    inputs:
      git-tag:
        required: true
        type: string
        description: Имя git-тега для повторной публикации (например, v1.2.3)
      npm-tag:
        required: false
        type: string
        default: replay
        description: Имя npm тега. Если не указать, то добавится тег :latest, что нежелательно при повторной публикации

jobs:
  publish:
    uses: nii-energomash/automation/.github/workflows/npm-package-publish.yml@v1
    with:
      mode: rebuild
      tag: ${{ inputs.git-tag }}
      npm-tag: ${{ inputs.npm-tag }}
      node-version: "20"
      npm-scopes-with-registers: |
        @${{ vars.NPM_SCOPE }}:registry=${{ vars.NPM_REGISTRY_URL }}
    secrets:
      node-auth-token: ${{ secrets.GH_PACKAGES_TOKEN }}
