# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Continuous Integration
description: >
  Workflow для push в feature-ветки (быстрый CI).
  Проверяем код, собираем build (не docker образ), но не сохраняем его.
  Ветка master (main) игнорируется

on:
  push:
    branches: ["**", "!master", "!main"]

jobs:
  ci:
    uses: nii-energomash/automation/.github/workflows/npm-ci.yml@v1
    with:
      node-version: "20"
      npm-scopes-with-registers: |
        @${{ vars.NPM_SCOPE }}:registry=${{ vars.NPM_REGISTRY_URL }}
        @${{ vars.NPM_ORG_SCOPE }}:registry=${{ vars.NPM_REGISTRY_URL }}
    secrets:
      node-auth-token: ${{ secrets.GH_PACKAGES_TOKEN }}
