# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# -----------------------------------------------------------------------------------------
# Для Pull Request используется заглушка, т.к.
# в Github Actions такой запрос подразумевает работу с недоверенным источником.
# По этой причине затруднена работа с секретами и приватными репозиториями пакетов.
# Затруднительно получить зависимости, без которых практически невозможно работать с кодом.
# Полноценный workflow можно использовать в локальной сети
# с публичными (в рамках локальной сети) пакетами.
# -----------------------------------------------------------------------------------------

name: Pull Request

on:
  pull_request:

jobs:
  pull-request-placeholder:
    runs-on: ubuntu-latest

    steps:
      - name: placeholder
        run: |
          echo "⬜ Pull Request PLACEHOLDER workflow.
          Для Pull Request используется заглушка, т.к.
          в Github Actions такой запрос подразумевает работу с недоверенным источником.
          По этой причине затруднена работа с секретами и приватными репозиториями пакетов.
          Затруднительно получить зависимости, без которых практически невозможно работать с кодом.
          Полноценный workflow можно использовать в локальной сети
          с публичными (в рамках локальной сети) пакетами."
