# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: NPM registries configure
description: >
  Настраивает регистры NPM для указанных scopes.
  Для работы получает массив строк, разделенный переносом строки, 
  и содержащий scope и адрес регистра в формате @<scope>:registry=<uri>.
  Например: @username:registry=https://npm.pkg.github.com

inputs:
  npm-scopes-with-registers:
    type: string
    required: false
    default: ""
    description: >
      Массив строк, разделенный переносом строки, 
      и содержащий scope и адрес регистра в формате
      @<scope>:registry=<uri>.
      Например: @username:registry=https://npm.pkg.github.com

runs:
  using: composite
  steps:
    - shell: bash
      env:
        SCOPES_WITH_REGISTERS: ${{ inputs.npm-scopes-with-registers }}
        NODE_AUTH_TOKEN: ${{ github.token }}
      run: |
        chmod +x "${{ github.action_path }}/registries-configure.sh"
        "${{ github.action_path }}/registries-configure.sh"
