# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: NPM code quality checks
description: >
  Проверка качества кода NPM-проекта
  (линтинг, тесты, сборка)

runs:
  using: composite
  steps:
    - name: 📦 Install dependencies
      shell: bash
      run: npm ci --no-fund

    - name: 📝 Lint
      shell: bash
      run: npm run lint

    - name: 🧪 Tests
      shell: bash
      run: npm test

    - name: 🛠️ Build
      shell: bash
      run: npm run build
