# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: (reusable) NPM CI
description: >
  Переиспользуемый workflow, описывающий Continuous Integration для NPM-проектов

on:
  workflow_call:
    inputs:
      publish-artifact:
        required: false
        type: boolean
        default: false
        description: Сохранять dist/ как артефакт

      ref:
        required: false
        type: string
        default: ""
        description: Указатель на коммит (используется при сборке по тегу)

      node-version:
        required: false
        type: string
        default: "20"
        description: Версия Node.js

      npm-scopes-with-registers:
        type: string
        required: false
        default: ""
        description: >
          Массив строк, разделенный переносом строки, и содержащий scope и адрес регистра в формате
          @\<scope\>:registry=\<uri\>. Например: @username:registry=https://npm.pkg.github.com

          Обратить внимание:

          Если в зависимостях присутствует пакет, расположенный в приватном регистре,
          то для такого приватного регистра требуется передать NPM токен.
          Однако, если пакет публичный, это может привести к ошибке 403 Forbidden

    secrets:
      node-auth-token:
        required: false
        description: Токен для приватных NPM регистров

jobs:
  reusable-ci:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref != '' && inputs.ref || github.ref }}

      - name: ✨ Setup Node.js (version ${{ inputs.node-version }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm

      - name: 📝 Configure npm registries
        uses: nii-energomash/automation/.github/actions/npm-registries-configure@master
        with:
          npm-scopes-with-registers: ${{ inputs.npm-scopes-with-registers }}
          node-auth-token: ${{ secrets.node-auth-token }}

      - name: 📦 Install dependencies
        shell: bash
        run: npm ci --no-fund

      - name: 📝 Lint
        shell: bash
        run: npm run lint

      - name: 🧪 Tests
        shell: bash
        run: npm test

      - name: 🛠️ Build
        shell: bash
        run: npm run build

      - name: 📦 Upload artifact
        if: ${{ inputs.publish-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
          retention-days: 1
